apiVersion: v1
kind: Service
metadata:
  name: d3-custom-test
  namespace: dkube
  annotations:
    getambassador.io/config: |-
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name:  rstudio
      prefix: /dkube/v2/ext/rstdio
      rewrite: /
      timeout_ms: 600000
      service: d3-custom-c9bc2c37-3e03-4c7f-bbfa-0b4ffbc01fbc.ocdkube:8787
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name:  rstudio1
      prefix: /dkube/v2/ext/
      rewrite: /
      timeout_ms: 600000
      service: d3-custom-c9bc2c37-3e03-4c7f-bbfa-0b4ffbc01fbc.ocdkube:8787
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name:  rstudio2
      prefix: /auth-sign-in
      rewrite: /dkube/v2/ext/rstdio
      timeout_ms: 600000
      service: d3-custom-c9bc2c37-3e03-4c7f-bbfa-0b4ffbc01fbc.ocdkube:8787
spec:
  clusterIP: None
  type: ClusterIP
